FROM golang:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    iproute2 \
    iputils-ping \
    iperf3 \
    libbpf-dev \
    libbpf1 \
    kmod \
    vim \ 
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

CMD ["/bin/bash"]
