[log]

log_level = "trace"

# --- Cgroup configuration ---
[[cgroups]]
path = "/opt/server"
gress = "ingress"
time_scale = "1s"
rate_bps = "10M"

[[cgroups]]
path = "/opt/client"
args = "kuro"
gress = "egress"
time_scale = "1s"
rate_bps = "10M"


# --- IP configuration ---
# each [[ip]]  defines IP/Port targets sharing same Strategy
[[ip]]
proto = "tcp"
gress = "ingress"
rate_bps = "1M"   # <------ NOTE: Bps here
time_scale = "1s"
interface = "lo"

# targets are used to define multiple IP/Port tuple
[[ip.rules]]
ip = "127.0.0.1"
port = 8080


[[ip.rules]]
ip = "127.0.0.1"
port = 9090


# [[ip]]
# proto = "udp"
# gress = "egress"
# rate_bps = "500K"
# time_scale = "100ms"
#
# [[ip.targets]]
# ip = "10.0.0.5"
# port = 53
