set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -DTOML_EXCEPTIONS=0")
set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -DTOML_EXCEPTIONS=0")
