apiVersion: v1
kind: Namespace
metadata:
  name: kuro-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuro-controller-sa
  namespace: kuro-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kuro-controller-role
rules:
  - apiGroups: ["simulation.kuro.io"]
    resources: ["networktopologies", "trafficcontrols", "networktopologies/status", "trafficcontrols/status"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources: ["pods", "nodes", "configmaps", "services", "events"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuro-controller-binding
subjects:
  - kind: ServiceAccount
    name: kuro-controller-sa
    namespace: kuro-system
roleRef:
  kind: ClusterRole
  name: kuro-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: kuro-controller
  namespace: kuro-system
spec:
  type: NodePort
  selector:
    app: kuro-controller
  ports:
    - name: grpc
      port: 9090
      targetPort: 9090
      nodePort: 30090
    - name: http
      port: 8080
      targetPort: 8088
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuro-controller
  namespace: kuro-system
  labels:
    app: kuro-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kuro-controller
  template:
    metadata:
      labels:
        app: kuro-controller
    spec:
      nodeName: kuro-dev-control-plane
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      
      serviceAccountName: kuro-controller-sa
      containers:
        - name: controller
          image: kuro-controller:dev
          imagePullPolicy: IfNotPresent
          command: ["/root/controller"]
          args:
            - "-grpc-port=9090"
            - "-http-port=8088"
            - "-metrics-bind-address=:8082"
          ports:
            - containerPort: 9090
            - containerPort: 8088
            - containerPort: 8082
            - containerPort: 8081
          env:
            - name: GOLOG_LOG_LEVEL
              value: "debug"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
