apiVersion: v1
kind: Pod
metadata:
  name: kuro-agent
  labels:
    app: kuro-agent
spec:
  hostNetwork: true       
  dnsPolicy: ClusterFirstWithHostNet
  nodeName: lab-cluster-control-plane 
  containers:
  - name: agent
    image: kuro-agent:dev
    imagePullPolicy: Never
    command: ["/usr/local/bin/agent"]
    securityContext:
      privileged: true   
    volumeMounts:
    - name: containerd-sock
      mountPath: /run/containerd/containerd.sock
    - name: bpf-fs
      mountPath: /sys/fs/bpf
      mountPropagation: Bidirectional 
  volumes:
  - name: containerd-sock
    hostPath:
      path: /run/containerd/containerd.sock
  - name: bpf-fs
    hostPath:
      path: /sys/fs/bpf
