apiVersion: v1
kind: Pod
metadata:
  name: test-pod-nginx 
  labels:
    experiment-id: "5" 
spec:
  containers:
  - name: nginx
    image: nicolaka/netshoot 
    command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
  labels:
    experiment-id: "5" 
spec:
  containers:
  - name: iperf-server
    image: nicolaka/netshoot
    command: ["iperf3", "-s"] 
