apiVersion: v1
kind: ServiceAccount
metadata:
  name: victoriametrics-sa
  namespace: kuro-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: victoriametrics-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "nodes/proxy", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: victoriametrics-binding
subjects:
  - kind: ServiceAccount
    name: victoriametrics-sa
    namespace: kuro-system
roleRef:
  kind: ClusterRole
  name: victoriametrics-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-config
  namespace: kuro-system
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'kuro-agent'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['kuro-system']
        
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: kuro-agent
            action: keep
          
          - source_labels: [__address__]
            regex: '(.*):(.*)'
            replacement: '${1}:8080'
            target_label: __address__
            
          - source_labels: [__meta_kubernetes_pod_node_name]
            target_label: node
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: victoriametrics
  namespace: kuro-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: victoriametrics
  template:
    metadata:
      labels:
        app: victoriametrics
    spec:
      serviceAccountName: victoriametrics-sa
      containers:
        - name: victoriametrics
          image: victoriametrics/victoria-metrics:v1.93.0
          args:
            - "-promscrape.config=/etc/prometheus/prometheus.yml"
            - "-storageDataPath=/victoria-metrics-data"
            - "-retentionPeriod=14d"
          ports:
            - name: http
              containerPort: 8428
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: storage-volume
              mountPath: /victoria-metrics-data
      volumes:
        - name: config-volume
          configMap:
            name: victoriametrics-config
        - name: storage-volume
          emptyDir: 
---
apiVersion: v1
kind: Service
metadata:
  name: victoriametrics
  namespace: kuro-system
spec:
  type: NodePort # 方便从外部访问写入或查询
  ports:
    - port: 8428
      targetPort: 8428
      nodePort: 30428
  selector:
    app: victoriametrics
