apiVersion: simulation.kuro.io/v1alpha1
kind: NetworkTopology
metadata:
  name: drone-swarm
  namespace: kuro-experiment
spec:
  nodeGroups:
    - name: leader
      replicas: 1
      image: nicolaka/netshoot
      labels:
        role: leader
      command: ["/bin/sh", "-c", "while true; do echo 'Leader is alive'; sleep 10; done"]

    - name: follower
      replicas: 2
      image: nicolaka/netshoot
      labels:
        role: follower
      command: ["/bin/sh", "-c", "while true; do echo 'Follower is alive'; sleep 10; done"]
