apiVersion: v1
kind: Pod
metadata:
  name: test-pod-server
  namespace: kuro-experiment  
  labels:
    app: test-workload
    role: server
spec:
  containers:
  - name: iperf-server
    image: nicolaka/netshoot
    command: ["iperf3", "-s"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-client
  namespace: kuro-experiment 
  labels:
    app: test-workload
    role: client
spec:
  containers:
  - name: iperf-client
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]
