syntax = "proto3";
package kuro;
option go_package = "kuro/proto";

service DataPlaneService {
  rpc StreamTrafficStats(stream TrafficStats) returns (StreamAck);
}

message TrafficStats {
  string node_name = 1;
  string iface_name = 2;

  uint64 total_accepted_bytes = 3;
  uint64 total_dropped_bytes = 4;
  uint64 total_accepted_packets = 5;
  uint64 total_dropped_packets = 6;

  double instant_rate_bps = 7;
  double smooth_rate_bps = 8;

  int64 timestamp = 9;
}


message StreamAck {
  bool ok = 1;
}

//
// service ControlPlaneService {
//   rpc ApplyTopology(ApplyTopologyRequest) returns (ApplyTopologyResponse);
//   rpc SetRateLimit(SetRateLimitRequest) returns (SetRateLimitResponse);
//   rpc SetNetem(SetNetemRequest) returns (SetNetemResponse);
// }
//
