// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type TcBucketState struct {
	_      structs.HostLayout
	Tokens uint64
	LastNs uint64
	Lock   struct {
		_   structs.HostLayout
		Val uint32
	}
	_ [4]byte
}

type TcFlowCounter struct {
	_               structs.HostLayout
	AcceptedBytes   uint64
	DroppedBytes    uint64
	AcceptedPackets uint64
	DroppedPackets  uint64
}

type TcNetemRule struct {
	_             structs.HostLayout
	LossThreshold uint32
	_             [4]byte
	JitterMs      uint64
	DelayMs       uint64
}

type TcTrafficRule struct {
	_          structs.HostLayout
	RateBytes  uint64
	BurstBytes uint64
}

// LoadTc returns the embedded CollectionSpec for Tc.
func LoadTc() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TcBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Tc: %w", err)
	}

	return spec, err
}

// LoadTcObjects loads Tc and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TcObjects
//	*TcPrograms
//	*TcMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTcObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTc()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TcSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcSpecs struct {
	TcProgramSpecs
	TcMapSpecs
	TcVariableSpecs
}

// TcProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcProgramSpecs struct {
	Gress *ebpf.ProgramSpec `ebpf:"gress"`
}

// TcMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcMapSpecs struct {
	BucketStateMap *ebpf.MapSpec `ebpf:"bucket_state_map"`
	BypassMap      *ebpf.MapSpec `ebpf:"bypass_map"`
	FlowCounterMap *ebpf.MapSpec `ebpf:"flow_counter_map"`
	NetemRuleMap   *ebpf.MapSpec `ebpf:"netem_rule_map"`
	RedirectMap    *ebpf.MapSpec `ebpf:"redirect_map"`
	TrafficRuleMap *ebpf.MapSpec `ebpf:"traffic_rule_map"`
	VxlanMap       *ebpf.MapSpec `ebpf:"vxlan_map"`
}

// TcVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TcVariableSpecs struct {
}

// TcObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcObjects struct {
	TcPrograms
	TcMaps
	TcVariables
}

func (o *TcObjects) Close() error {
	return _TcClose(
		&o.TcPrograms,
		&o.TcMaps,
	)
}

// TcMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcMaps struct {
	BucketStateMap *ebpf.Map `ebpf:"bucket_state_map"`
	BypassMap      *ebpf.Map `ebpf:"bypass_map"`
	FlowCounterMap *ebpf.Map `ebpf:"flow_counter_map"`
	NetemRuleMap   *ebpf.Map `ebpf:"netem_rule_map"`
	RedirectMap    *ebpf.Map `ebpf:"redirect_map"`
	TrafficRuleMap *ebpf.Map `ebpf:"traffic_rule_map"`
	VxlanMap       *ebpf.Map `ebpf:"vxlan_map"`
}

func (m *TcMaps) Close() error {
	return _TcClose(
		m.BucketStateMap,
		m.BypassMap,
		m.FlowCounterMap,
		m.NetemRuleMap,
		m.RedirectMap,
		m.TrafficRuleMap,
		m.VxlanMap,
	)
}

// TcVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcVariables struct {
}

// TcPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTcObjects or ebpf.CollectionSpec.LoadAndAssign.
type TcPrograms struct {
	Gress *ebpf.Program `ebpf:"gress"`
}

func (p *TcPrograms) Close() error {
	return _TcClose(
		p.Gress,
	)
}

func _TcClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tc_bpfeb.o
var _TcBytes []byte
